### ISSUE TITLE
Can't paint with a category

### ISSUE THREAD

**Issue by thommor** [Portponky/better-terrain#12]
Thanks fo what looks like a great terrain plugin.

Following the README and your YouTube videos I believe I should be able to paint using a category which contains one or more "Matching Tiles" terrains, however when I try to paint with it nothing happens and the tiles remain blank. There are no apparent errors to explain this either.

It works fine if I paint the walls and roof terrains indepentently but not if I use the category terrain.

Am I doing something wrong?

<img width="340" alt="Screenshot 2023-06-05 at 08 13 28" src="https://github.com/Portponky/better-terrain/assets/45167957/49aa0d53-3700-4b3f-8172-71ee8bc83ca4">
<img width="333" alt="Screenshot 2023-06-05 at 08 13 38" src="https://github.com/Portponky/better-terrain/assets/45167957/a8dc3cd2-6b04-414c-b8d5-60f977932bdd">
<img width="329" alt="Screenshot 2023-06-05 at 08 13 47" src="https://github.com/Portponky/better-terrain/assets/45167957/a44a4c2b-9ced-4a16-90d3-d96163c5131f">
<img width="160" alt="Screenshot 2023-06-05 at 08 13 55" src="https://github.com/Portponky/better-terrain/assets/45167957/90cf0f61-0183-4acb-90a9-1b46c47a94a1">

**Comment by thommor** [comment]
So, my understanding was if my walls terrain and roof terrain were part of the same category then painting with the category would place tiles from both terrains using the combined rules, maybe this is not the case?

My hope had been that if I was to drag a square/rectangle of the category that the outer edges would use the correct wall tiles and the middle would use the roof tiles. I could do that as one terrain if it wasn't for the front facing wall being two tiles high which complicated things. Is this something thats not possible?

**Comment by Portponky** [comment]
That would be an awesome feature, but it can't do it. It's a very complicated problem.

For example, taking your tiles from above:
![image](https://github.com/Portponky/better-terrain/assets/33663279/44c30495-e71e-4088-a345-bafbbc3f92ba)

The highlighted cell could fit either a wall (as shown) or the roof tile. As a human, it's easy to tell that the wall tile goes there visually, but the roof tile fits the constraints just as well. It's just as valid when you consider that tile in isolation.

To solve it correctly (or in the general case), cells would need to propagate constraints between each other, and a constraint solver algorithm would need to run over them. Constraint satisfaction is not fast, and any given set of constraints does not necessarily have a solution.

That's why it doesn't do it, sorry if that's a bit disappointing.

**Comment by thommor** [comment]
It is a bit dissapointing but I completely understand.

As mentioned above using the walls and roof terrains I can manually create the effect I'm after but as the plan is to procedurally generate the game world I'll have to calculate the roof tiles to add progrmatically at generation.

Thanks for the help and insight and thanks for the plugin, even though it can't do my rather completed case it is still making the rest of my development easier.

Happy for you too close this issue if you wish

**Comment by Portponky** [comment]
I'll close it when I get around to giving a warning or error to the user when they attempt to paint in a way that might not make sense.

**Comment by Portponky** [comment]
As an aside, the new decoration system allows automatic placement of surrounding tiles, which lets you draw this kind of wall with relative ease. I didn't have the full tileset but here's a quick demo:


https://github.com/Portponky/better-terrain/assets/33663279/d40bfda1-4bce-416c-b0a4-06693b5153b7
