### ISSUE TITLE
Decoration tiles

### ISSUE THREAD

**Issue by Portponky** [Portponky/better-terrain#25]
This is an issue to discuss the design of decoration tiles, as based on @torcado194 's PR implementation.

![Two different blue terrains with surrounding empty tiles marked](https://github.com/Portponky/better-terrain/assets/33663279/3e405c40-8773-4140-b8bf-a08c127b176c)

Here are two terrains with the empty cells marked.

![Two different blue terrains with common neighboring empty tiles marked](https://github.com/Portponky/better-terrain/assets/33663279/c0d511b9-4780-4956-9051-2de00402de2a)

There cells in particular interest me, as they are common to different terrains. This situation is very simplified, but the general principle can show up in any place and with multiple terrains (up to 8, in a very contrived way). A more classic example would be a fringe around a terrain type.

I like the idea of having a specific type of terrain to act in-place of empty tiles. The built-in system of having optional center bits is very, very confusing and does not appear to give a clear functional advantage.

Having multiple different decoration-type terrains does not appear to have a strong reason. Why make 2 types instead of 1? The only reason that stands out is to categorize different types of decoration and apply them to different terrain types as needed. However, Better Terrain already has a system for categorizing terrain (category types), so this advantage isn't clear cut to me.

Here's my current idea for how decorations could work:

![Example terrain menu](https://github.com/Portponky/better-terrain/assets/33663279/3155f570-503c-44bb-8512-d377e83d0c14)

Every terrain has a built-in 'decoration' type, which you can't change. It sits first in the list (or last?). You can't make more decoration types, this is just a special built-in type.

The decoration type acts exactly like a 'match tiles' terrain, but is considered equivalent to empty tiles. You can assign tiles to be decoration, and then set up their peering bits appropriately. You can't use the decoration type as a peering type (anywhere). For each decoration tile, you should give it peering bits for other terrains/categories to determine how it will appear.

This would keep all decorations unified (as all decorations are equivalent in terms of function), and visually/logically put them in one place for the user. It would also be a reversal of torcado's design, instead of assigning decorations to a terrain, you assign terrain (peering) to the decorations. The value there is that decorations can function between multiple terrain.

I am keen to get feedback on this. I am being cautious because once this is implemented and merged, the behaviour is locked in. Let me know what you think.

**Comment by torcado194** [comment]
I think this is a totally fine alternative implementation of the idea.
I went with the solution I did mostly for simplicity with implementation (and computation speed). I started out writing it in the way you have it here, where decoration peering bits were assigned per source terrain, but that along with correct probability handling with multiple different neighbor types became annoyingly complex, so I changed trajectory. If you can come up with an implementation that handles all of that ideally in this version, then I'm on board.
I agree having the ability to have mixed terrains for a single decoration tile is good, which my version can only support with multiple layers and overlapping.
I think the only downside i see with this (aside from implementation complexity and potential performance problems) is lack of organization, just that every decoration is included in one entry. But I can't think of a better setup in this case, so I don't know if that level of organization is really necessary here.

**Comment by Portponky** [comment]
Hi, sorry for the slow pace. I recently started a new job and haven't had much time. I managed to implement a reasonably clean implementation of the idea I outlined above:

https://github.com/Portponky/better-terrain/assets/33663279/932a3148-f06c-469e-9c4b-81295fa571de

There are still a number of places in the code I haven't updated, so it's a little glitchy in terms of UX, but the matching seems to work pretty well.

Part way through I decided that making 'decoration' peering bits is probably a good idea. People liked the 'ignore' bits in Godot 3's autotiler, and the decoration peering bits achieve the same function.

**Comment by torcado194** [comment]
No need to apologize :) thank you for taking the time to work on this!

This looks great! How does it handle tile probabilities and 

(This is something particularly on my mind because my solution is a bit non-obvious, since *empty tile* is a potential outcome unique to decorations, it uses the highest probability of each choice for its basis. so, if each choice has a 20% probability, the final tile is filled 20% of the time, and the individual choices are weighted against each other as they would normally)

**Comment by Portponky** [comment]
I haven't tackled it yet, but I am aware you have a rather good result (as demonstrated in your video). What situations would not be handled well by that case?

**Comment by torcado194** [comment]
There's a minor but somewhat annoying consequence of decoration tiles with <1 probability with multiple neighbors, which causes this behavior:
![image](https://github.com/Portponky/better-terrain/assets/9218934/9491f8ba-8663-4a55-8cd5-3168bf9214ca)
This isn't incorrect per se, but ideally (imo) the placed decorations between rows wouldn't always be matched top+bottom tiles and instead be a mix of top, bottom, and both. So essentially, the "empty tile" state outcome isn't chosen per-choice in the tile list but rather per-neighbor. The solution would require checking every permutation of peering bits of the decoration terrain that are subsets of the neighbor set, and using all of those potential tiles in the weighted list. (But beyond that the process i described would remain the same)

However, this can be worked around fairly easily. it just requires the user to manually do that work, by setting up duplicate tiles for all the permutations (so in this example i'd duplicate all the bottom-side and top-side decoration tiles and give them all top+bottom peering bits). It's just potentially a lot of work. 

I don't necessarily expect this to be handled, and the processing time cost might outweigh the benefit anyway, but it'd be cool to have the option! (and now that i think about it, making it an option may be the better idea if implemented at all. since this also might be unwanted behavior by the user, that e.g. they wouldn't want a bottom-side tile in an inside corner)

**Comment by Portponky** [comment]
With my current method, you don't actually need alternate tiles to set up this arrangement:

**Comment by Portponky** [comment]
With my current method, you don't actually need alternate tiles to set up this arrangement:

![Example grass tufts](https://github.com/Portponky/better-terrain/assets/33663279/1a9519e9-03b5-4338-b69b-42796c6e6c05)

Excuse my art, lol. Setting up the peering bits on the grass to both top and bottom, but then adding in extra deco peering bits breaks the tie:

![Decoration peering bits](https://github.com/Portponky/better-terrain/assets/33663279/3244d8a0-f3df-414a-b288-c73323aa0b6a)

I'm not sure if it can be set up with the probability distribution quite right, but that can certainly be done with alt tiles.

**Comment by torcado194** [comment]
Oh alright, interesting! Yeah seems like a bit of a hack, but if it works for that case then nice :)

**Comment by Portponky** [comment]
Okay, I've pushed my work to the branch https://github.com/Portponky/better-terrain/tree/decorations

I'm going to do some tidy up, mostly on how tilesets are iterated, but it should be fully functional. If you get a chance to try it, let me know what you think. I used your icon, hope that's okay.

Note, at the moment, the branch doesn't have any update code, because I want to ideally roll all the recent changes into one update version. Only use it with newly created tilemaps.

**Comment by torcado194** [comment]
Very nice! Thank you for working on this :) and you're more than welcome to use my icon!

Some notes:
- It looks like probability tiles aren't working as I expect, assuming that's something you meant to have implemented in this version. Just that the probability of a tile existing is cumulative rather than based on the highest probability in the list. so it'll always place a tile when choosing between two or more 50% tiles. This should also carry over to choices between multiple terrains (imo), so that one terrain with 10 top-side decoration variants below another terrain with only 1 bottom-side decoration isn't biased to the larger set (assuming the individual probabilities are the same. otherwise bias just by the difference). e.g.
![image](https://github.com/Portponky/better-terrain/assets/9218934/a91c22a2-3fd3-4a65-80f0-1cf1f825b82f)
- I'm getting a `No TileSet atlas source with id -1. at: (scene\resources\tile_set.cpp:550)` error when adding or removing a tile from a terrain, haven't looked into the cause.
- I'm not entirely sure what the purpose is of painting peering bits on the decoration terrain, i'm interested to see a usecase or explanation.

Other than that it seems to work great from my testing! Being able to assign multi-terrain decorations is very useful.

I have some ideas for distinguishing the look of the Decoration terrain entry that i'd love to include in the Icons PR once this is added.

**Comment by torcado194** [comment]
It looks like you just need to change https://github.com/Portponky/better-terrain/blob/e882d4d6436f91d6d93984b63f3143ac23cded6d/addons/better-terrain/BetterTerrain.gd#L220
to
`var max_weight = choices.reduce(func(a, c): return maxf(a, c[4]), 0.0)`, which solves the first of my issues in that note. (it looks like it was a mistake anyway, since currently it's a duplicate with the line a few lines down. thinking about it now, this may technically be more efficient with a single loop that calculates both sum and max. not a big deal either way)
The other part of that note is still present, i'd have to think of a good solution to that.

**Comment by Portponky** [comment]
Yeah, it was a copy paste error when I was tidying up the code. Fixed.

**Comment by torcado194** [comment]
Nice, thanks.
```
if c[0] < 0:
    continue
```
at 173 in `BetterTerrain.gd` fixes the error I was getting.

**Comment by Portponky** [comment]
Yes, I need to generally address the lack of checking of source ids and valid sources in a number of places.

**Comment by torcado194** [comment]
here's a modified `_` that solves the other half of my first point:
```gd
func _weighted_selection(choices: Array, apply_empty_probability: bool, separate_terrains: bool = true):
	if choices.is_empty():
		return null
	
	if apply_empty_probability:
		var max_weight = choices.reduce(func(a, c): return maxf(a, c[4]), 0.0)
		if max_weight < 1.0 and randf() > max_weight:
			return [-1, Vector2.ZERO, -1, null, 1.0]
	
	if choices.size() == 1:
		return choices[0]
	
	var weights = []
	var weight = 0.0
	if separate_terrains:
		var terrains_total:Dictionary = {}
		for c in choices:
			if not terrains_total.has(c[0]):
				terrains_total[c[0]] = 0
			terrains_total[c[0]] += 1
		
		for c in choices:
			var w = c[4] / terrains_total[c[0]]
			weights.push_back(w)
			weight += w
	else:
		for c in choices:
			weights.push_back(c[4])
			weight += c[4]
	
	if weight == 0.0:
		return choices[randi() % choices.size()]
	
	var pick = randf() * weight
	for i in range(choices.size()):
		if pick < weights[i]:
			return choices[i]
		pick -= weights[i]
	return choices.back()
```
(this doesnt have to be an optional parameter)
essentially this adjusts each choice weight by the total count within that tile's terrain. now tiles of equal probability will be chosen equally between two terrains, and tiles with lower probability in one terrain relative to another terrain (even with more possible alternative options) will be chosen less often

**Comment by Portponky** [comment]
That doesn't quite make sense to me because c[0] is the atlas id, not the terrain id. I could store the terrain id, but all decorations have the same id anyhow. I get what you're going for though, I'll have a think to see if I can come up with a general approach to the issue.

**Comment by torcado194** [comment]
Oh, my bad. I did a simple debug and my atlases happened to line up with my terrain ids (hard to know since the structure isn't described anywhere! unless i missed it).
Hm yeah you're right, the decoration tiles aren't part of the terrain, just the peering bits. It could use the tile's TileSet instead, though I do think terrain would be more accurate.

**Comment by torcado194** [comment]
Here's another idea, which I was just going to write as a comment but decided to try implementing anyway. This groups tiles by their peering bit dictionary. so if any two or more tile's peering bits are identical their weights will be adjusted together, otherwise they will be weighted the same as they currently are (no adjustments).
(This assumes that the peering bit dictionaries on these objects have a stable ordering, otherwise this will need to sort the keys and the values, which might be pretty harsh processing-wise unless this step is done elsewhere)
I think this is probably a similarly ideal grouping to terrain id or TileSet id, since two tiles with differing peering bits will be scored differently in the previous step anyway.

```gd
func _weighted_selection(choices: Array, apply_empty_probability: bool, separate_terrains: bool = true):
	if choices.is_empty():
		return null
	
	if apply_empty_probability:
		var max_weight = choices.reduce(func(a, c): return maxf(a, c[4]), 0.0)
		if max_weight < 1.0 and randf() > max_weight:
			return [-1, Vector2.ZERO, -1, null, 1.0]
	
	if choices.size() == 1:
		return choices[0]
	
	var weights = []
	var weight = 0.0
	if separate_terrains:
		var neighbor_set_list:Dictionary = {}
		var terrains_total:Dictionary = {}
		for c in choices:
			var neighbor_set_key = str(c[3])
			if not neighbor_set_list.has(c):
				neighbor_set_list[c] = neighbor_set_key
			if not terrains_total.has(neighbor_set_key):
				terrains_total[neighbor_set_key] = 0
			terrains_total[neighbor_set_key] += 1
		
		for c in choices:
			var w = c[4] / terrains_total[neighbor_set_list[c]]
			weights.push_back(w)
			weight += w
	else:
		for c in choices:
			weights.push_back(c[4])
			weight += c[4]
	
	if weight == 0.0:
		return choices[randi() % choices.size()]
	
	var pick = randf() * weight
	for i in range(choices.size()):
		if pick < weights[i]:
			return choices[i]
		pick -= weights[i]
	return choices.back()
```

**Comment by torcado194** [comment]
I'm converting the dictionary to a string for comparison, if it wasn't clear.

Yeah, I'm not sure. I think it can be ignored for now and looked into later, if at all. It's a fairly niche situation to handle.

**Comment by Portponky** [comment]
I think the arrays will come out of the caching function sorted, though I don't recall for sure.

After thinking about it, I believe that using alternate tiles should allow a good variety of probabilities, enough to get close to any common use case. I will probably leave it as-is for just now, and take it forwards later if inspiration strikes.

@torcado194 if you are happy with this, could you open a PR for the updated icons only into the `decoration` branch? Then we can formulate the 0.2 version of the terrain meta to include both decorations and the terrain icons.

The big difference is that the terrain is categorized into `TileCategory.EMPTY` = -1 for anything empty/decoration, and `TileCategory.NON_TERRAIN` = -2 for any other tile. The tile view in the dock has a decoration type at the end, but it can't be moved or edited, and there are no changed to the terrain properties popup.

**Comment by torcado194** [comment]
Sounds good to me :)

Yep, I can do that! should I include the random seed changes in that PR as well, or a different PR?

**Comment by Portponky** [comment]
Up to you, as it won't affect the meta version. Thanks a ton, by the way. You've made huge improvements to this plugin.

**Comment by torcado194** [comment]
You're very welcome! The plugin has been a great boost to my workflow :)

**Comment by Portponky** [comment]
Closing, as this is feature complete for a first version.
