### ISSUE TITLE
Feature request: Shortcuts and picker

### ISSUE THREAD

**Issue by PiotrTekieli** [Portponky/better-terrain#56]
I might simply be missing something, but it would be nice if the terrain drawing tools had shortcuts that mirrored the default TileMap ones ( Draw tool - D / Line tool - L / Rect tool - R / Bucket tool - B )

A Picker functionality would also be really useful, in the default TileMap it's P or hold Ctrl, in this case it'd select the terrain type the selected tile belongs to

**Comment by Portponky** [comment]
Implemented in latest commit.

The shortcut R for rectangle tends to turn the editor into ruler mode. Unfortunately, the mechanisms by which this happens aren't easily manipulated through GDScript (and even then, the tilemap dock sometimes goes to rule mode instead of selecting rectangles). As such, I added C as alternative.

Picker is available with ctrl-click, but has no individual tool.

Will update addon library version.

**Comment by Portponky** [comment]
Updated asset lib version a while back, so this is complete.
