### ISSUE TITLE
Tiles 1 away from a corner don't connect correctly

### ISSUE THREAD

**Issue by Wcubed** [Portponky/better-terrain#64]
First of all, I'd like to thank you for the awesome plugin! This is exactly how I expected the terrain tiling in Godot 4 to work :)

I noticed something weird. In my setup I have two terrain types: grass and water.

The terrain has a rectangular lake, inside a large patch of grass:
![image](https://github.com/Portponky/better-terrain/assets/7442115/cb03eca6-6212-42ce-81c7-a3d0aec558b2)
The strange thing is that the tiles near the corners (marked with the red arrows) will randomly pick between a straight transition piece, or a corner piece. When filling the lake repeatedly with "shuffle" enabled, I get different arrangements of these tiles. The rest of the tiles stay rock solid, even the actual corner pieces.

This is my terrain setup:
Connection rules for grass:
![image](https://github.com/Portponky/better-terrain/assets/7442115/87abc01e-e8a4-4a12-9554-a48d25c0074e)
Connection rules for water:
![image](https://github.com/Portponky/better-terrain/assets/7442115/acb5d0e1-10a3-46da-adb3-089e6a6eaedb)

From the connection rules I would assume that the only valid pieces for near the corners, would be the straight transition pieces.
Am I misunderstanding how the connection rules function? Or is there a bug in this specific situation.

Godot version: v4.2.1
Plugin version: v1.0

-------
EDIT

As an experiment, I changed the connection rules to the following:
![image](https://github.com/Portponky/better-terrain/assets/7442115/0db68567-e2ce-4d3f-9c97-7d86325abcc9)
![image](https://github.com/Portponky/better-terrain/assets/7442115/d3273e37-d6b6-41c5-bbf5-55c9057083cf)

Now the lake _does_ work, but it seems to get confused at the ends of this T shaped water section. It always fills those with full land, while according to the connections I would assume the straight transition pieces fit perfectly.
![image](https://github.com/Portponky/better-terrain/assets/7442115/f22ada91-5eca-49f6-ac24-61cf624a3970)

Thanks again for the great work!

**Comment by Portponky** [comment]
Hi,

For the first example, let's have a look at the top left corner, and the tile to the right of it. It's chosen the correct tile in your screenshot, but it's a 50/50 chance that it will. Here's why.

![image](https://github.com/Portponky/better-terrain/assets/33663279/99682153-0597-4b99-8063-55ff9429c00d)

There's the neighboring area of the tile, and underneath I have drawn it with just colors. Then to the right, there's the edge and the corner piece. Both of them match 7/8 neighbors, and are incorrect for 1/8 neighbors. It's different in both cases, but they score the same - not a perfect match, but close. Because they score the same, Better Terrain picks one at random based on their random weights (by default 50/50). That's why it is acting this way.

The second example is better, as it specifies less matching rules. That means there are less misses. However, the edges still only match against three water tiles, so in those narrow examples, they will cause at least 2 misses, where as the plain grass tile only causes 1 miss.

A more minimalist rule set might work better for you. Something like this:

![image](https://github.com/Portponky/better-terrain/assets/33663279/c104ee9a-4034-4cfc-a383-08504b84deb7)

The plain grass doesn't match against anything, it's just the default for grass. Edges occur when grass is adjacent to water. Corners occur when there is diagonal water, but it's got grass on both sides.

Even with those rules (rotated for all the tiles) there are still combos for which there are no good tile placements, but that might be suitable for your needs.

**Comment by Wcubed** [comment]
Thank you, that makes _so_ much more sense now.

I see now I was thinking backwards about connecting tilesets. Because it doesn't have a tile for every single occurence, filling in every single connection rule forces it to pick between two that both don't entirely work. Even though one will work, but in over-constraining I told it "no this tile can't work here".

Telling it instead "use this tile, unless there is a tile that fits better", made it work :)
