### ISSUE TITLE
Help understanding categories

### ISSUE THREAD

**Issue by no-na** [Portponky/better-terrain#76]
Hello, I have two categories, with my half-cube tiles in the purple category and my full-cube tiles in the blue category.
![image](https://github.com/Portponky/better-terrain/assets/9628371/b3a447e1-3cd2-44f3-a46d-ee8cebec9fee)

I am having issue with my 'full-flat' terrain, which is a member of the blue full-cube category. There are four tiles in this terrain.
![image](https://github.com/Portponky/better-terrain/assets/9628371/fe66d485-6a36-488d-89bd-64db2db2db1f)

I've set up their connecting types within the full cube category like this, so that outlines appear along the northern edges of the continuous terrain, and when painting, it appears as expected.
![image](https://github.com/Portponky/better-terrain/assets/9628371/e5712e6b-4d87-4515-9f39-c871f5d4a9ae)
![image](https://github.com/Portponky/better-terrain/assets/9628371/94b6f40b-6450-4e13-b38d-49993887e8f5)

But when I add their connecting types to the half cube category, it causes ambiguity when painting, even though no half cube category terrains are present.
![image](https://github.com/Portponky/better-terrain/assets/9628371/96b1d17a-aeaf-4c9f-840f-8df878cb45cd)
![image](https://github.com/Portponky/better-terrain/assets/9628371/97edc334-40ee-48a2-8c03-23518257b11d)

Do you know why this is happening, and what I should be doing instead? My goal is to be able to get this look:
![image](https://github.com/Portponky/better-terrain/assets/9628371/cf437606-d259-4a12-97fe-578f1e6f906e)

Thank you for this plugin and any advice you can give!

**Comment by Portponky** [comment]
Hi, this is quite a complicated setup, so I'm not sure I fully understand what is going on. I think I see what the problem is, which is to do with how multiple peering bits are applied. If I understand it right, these are the peering bits for one of the flat tiles for both categories:

![image](https://github.com/Portponky/better-terrain/assets/33663279/10484b2f-93f6-41ca-ada1-0db0a96cba40)

This means it will look for purple matches in NW and NE, and it will look for purple or blue matches in SW and SE. If any of these matches aren't present, it will score negatively, and if they are present, it will score positively. Unset peering bits are not scored.

First up, you don't need to match SW and SE because they don't affect the tile choice.

Second, you don't need to match against half-height tiles, because whether they are present or not shouldn't change which tile is chosen.

For the half height tiles, you should match both blue and purple in the NW and NE directions where appropriate.

I'm not sure how this will affect the different sloped pieces, let me know how you get on.

**Comment by no-na** [comment]
Thanks for explaining! I got it working now:
![image](https://github.com/Portponky/better-terrain/assets/9628371/7a6537e9-1899-4846-b85a-653a4cdaaf9c)
